# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_EikonDownloader_wrappers", use_symbols = TRUE, package_name = "EikonDownloader")

#' @docType package
#' @usage NULL
#' @useDynLib EikonDownloader, .registration = TRUE
NULL

rust_get_dg <- function(instruments, fields, param, settings, api, port) .Call(wrap__rust_get_dg, instruments, fields, param, settings, api, port)

rust_get_ts <- function(rics, fields, Frq, Start_Date, End_Date, api, port) .Call(wrap__rust_get_ts, rics, fields, Frq, Start_Date, End_Date, api, port)

