# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_EikonDownloader_wrappers", use_symbols = TRUE, package_name = "EikonDownloader")

#' @docType package
#' @usage NULL
#' @useDynLib EikonDownloader, .registration = TRUE
NULL

#' Eikon status
#' @export
status <- function(api, ip, port) .Call(wrap__status, api, ip, port)

rust_get_dg <- function(instruments, fields, param, api, ip, port) .Call(wrap__rust_get_dg, instruments, fields, param, api, ip, port)


# nolint end
